package eshop.user.dal.dao.model;

public class UserUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.tanantId
     *
     * @mbggenerated
     */
    private String tanantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.tanantId
     *
     * @return the value of user_user.tanantId
     *
     * @mbggenerated
     */
    public String getTanantid() {
        return tanantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.tanantId
     *
     * @param tanantid the value for user_user.tanantId
     *
     * @mbggenerated
     */
    public void setTanantid(String tanantid) {
        this.tanantid = tanantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.userId
     *
     * @return the value of user_user.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.userId
     *
     * @param userid the value for user_user.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}