package eshop.user.dal.dao.model;

public class UserUser extends UserUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.userName
     *
     * @return the value of user_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.userName
     *
     * @param username the value for user_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }
}