package eshop.user.dal.dao.mapper;

import eshop.user.dal.dao.model.UserUser;
import eshop.user.dal.dao.model.UserUserExample;
import eshop.user.dal.dao.model.UserUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

public interface UserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int countByExample(UserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int deleteByExample(UserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insert(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insertSelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    List<UserUser> selectByExample(UserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    UserUser selectByPrimaryKey(UserUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserUser record, @Param("example") UserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserUser record, @Param("example") UserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserUser record);
}